name: generate-snake-game

on:
  schedule: # exécute automatiquement chaque jour
    - cron: "0 0 * * *"
  workflow_dispatch: # permet de lancer manuellement depuis l’onglet Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: generate-snake-game
        uses: Platane/snk@v3.4.1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Publie les fichiers générés dans la branche "output"
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
